unsigned int xa_hide_tab_close_buttons;
char xa_nickcommand[256];
char xa_urlcommand[256];
char xa_channelcommand[256];
char xa_sleepmessage[256];
unsigned int xa_tab_completion;
unsigned int xa_checkvers;
unsigned int xa_scrolling_completion;
unsigned int xa_show_myservers;
char xa_default_charset[256];
unsigned int xa_outline_width;
unsigned int xa_text_manual_indent_chars;
unsigned int xa_partonsleep;
long tab_left_key;
long tab_left_modifiers;
long tab_right_key;
long tab_right_modifiers;
unsigned int xa_auto_away;
unsigned int xa_auto_away_delay;
unsigned int xa_paned_pos;
