CONV = gdk-pixbuf-csource

LIST =	aboutpng about.png \
			bookpng book.png \
			hoppng hop.png \
			oppng op.png \
			purplepng purple.png \
			redpng red.png \
			voicepng voice.png \
			xchatpng ..\..\xchat.png

all: inline_pngs.h

inline_pngs.h:
	$(CONV) --build-list $(LIST) > inline_pngs.h

clean:
	del *.h
