all:
	copy ..\config.h.w32 ..\config.h
	copy ..\plugins\xchat-plugin.h common
	@cd pixmaps
	@-$(MAKE) /NOLOGO -f makefile.msc $@
	@cd ..\common
	@-$(MAKE) /NOLOGO -f makefile.msc $@
	@cd ..\fe-gtk
	@-$(MAKE) /NOLOGO -f makefile.msc $@

clean:
	del common\*.obj
	del common\xchatcommon.lib
	del fe-gtk\*.obj
	del fe-gtk\xchat.exe
	del fe-gtk\xchat.rc
	del fe-gtk\xchat.RES
	del pixmaps\*.h
