include "..\makeinc.msc"

all: $(COMMON_OBJECTS) xchatcommon.lib

xchatcommon.lib: $(COMMON_OBJECTS)
	lib -out:xchatcommon.lib $(COMMON_OBJECTS)

.c.obj:
	$(CC) $(CFLAGS) $(GLIB) /c $<

clean:
	del *.obj
	del xchatcommon.lib
