prefs.xa_text_manual_indent_chars = 15;
prefs.xa_outline_width = 150;
prefs.xa_partonsleep = 1;
prefs.xa_line_height = 120;
prefs.xa_auto_away = 0;
prefs.xa_auto_away_delay = 10;
prefs.xa_tab_completion = 1;
prefs.xa_bounce_continuously = 1;
prefs.xa_input_grammar = 1;
prefs.xa_input_autocorrect = 1;
strcpy (prefs.xa_default_charset, "utf-8");
strcpy (prefs.xa_urlcommand, "browser %s");
strcpy (prefs.xa_nickcommand, "query %s");
strcpy (prefs.xa_channelcommand, "join %s");
strcpy (prefs.xa_sleepmessage, "This computer has gone to sleep");
char *downloaddir = get_downloaddir_fs();
strcpy (prefs.dcc_completed_dir, downloaddir);
free(downloaddir);
